language: r
sudo: required
cran: http://cran.rstudio.com
dist: trusty
cache: packages

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

matrix:
  include:
    - r: release
      r_github_packages: adamdsmith/itistools
      r_github_packages: adamdsmith/nwrspp
    - r: devel
      r_github_packages: adamdsmith/itistools
      r_github_packages: adamdsmith/nwrspp
    - r: oldrel
      r_github_packages: adamdsmith/itistools
      r_github_packages: adamdsmith/nwrspp

notifications:
  email:
    on_success: change
    on_failure: change
