language: r
sudo: required
cran: http://cran.rstudio.com
dist: trusty
cache: packages
warnings_are_errors: false

matrix:
  include:
    - r: release
      r_github_packages: adamdsmith/itistools
    - r: devel
      r_github_packages: adamdsmith/itistools
    - r: oldrel
      r_github_packages: adamdsmith/itistools

notifications:
  email:
    on_success: change
    on_failure: change
